### ISSUE TITLE
Directory - Enter a location by pinning onto a map (instead of postcode)

### ISSUE THREAD

**Issue by Fran-Uk** [folklabs/cpneighbours#3] opened 2016-05-02 09:47 UTC
Some locations, eg events in the park, need to be identified by pinning a point on a map, and post code is too crude a value, or not available.

Option to define a location as "pin on map" (or similar).

**Comment by pmackay** [comment] 2016-05-05 09:22
This and other map issues will need looking at as part of the updates to mapping, which I'm planning to look into.

**Comment by pmackay** [comment] 2016-12-05 14:39
Duplicate of https://github.com/folklabs/openlocal/issues/19.

**Closed as completed by pmackay** 2016-12-05 14:39 UTC
